version: "3.9"

services:
  pg-main:
    image: ${POSTGRES_IMAGE}
    container_name: pg-main
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA_PATH}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata-main:${PGDATA_PATH}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata-main:
